/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: '#2563eb',
          foreground: '#ffffff',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        robotics: {
          darkest: '#070b12',
          dark: '#0c1322',
          surface: '#111a2e',
          card: '#162238',
          border: '#1f2e4d',
          borderLight: '#2a3d66',
          accent: '#0284c7',
          accentLight: '#38bdf8',
          teal: '#0d9488',
          emerald: '#059669',
          amber: '#d97706',
          orange: '#ea580c',
        },
        eyantra: {
          orange: '#ea580c',
          amber: '#f59e0b',
          cyan: '#0284c7',
          blue: '#2563eb',
          electricBlue: '#38bdf8',
          violet: '#7c3aed',
          purple: '#6d28d9',
          teal: '#0f766e',
          emerald: '#059669',
          gold: '#d97706',
          dark: '#070b12',
          darkCard: '#0f172a',
          darkBorder: '#1e293b',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'subtle-blue': '0 2px 12px -2px rgba(37, 99, 235, 0.25)',
        'subtle-cyan': '0 2px 12px -2px rgba(14, 165, 233, 0.25)',
        'subtle-emerald': '0 2px 12px -2px rgba(16, 185, 129, 0.25)',
        'subtle-orange': '0 2px 12px -2px rgba(234, 88, 12, 0.25)',
        'tech-card': '0 4px 20px -2px rgba(15, 23, 42, 0.06)',
        'tech-card-dark': '0 4px 24px -2px rgba(0, 0, 0, 0.5)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.98)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        circuitPulse: {
          '0%, 100%': { opacity: '0.4', strokeDashoffset: '0' },
          '50%': { opacity: '0.8', strokeDashoffset: '-8' },
        },
        radarSweep: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        beaconBlink: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.4', transform: 'scale(1.15)' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-up': 'fadeInUp 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'circuit-pulse': 'circuitPulse 4s ease-in-out infinite',
        'radar-sweep': 'radarSweep 6s linear infinite',
        'beacon-blink': 'beaconBlink 2.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
